project_id = "ynzwbttkyjhrqeloquhu"

[functions.ai-teacher-chat]
verify_jwt = true

[functions.suggest-topics]
verify_jwt = true

[functions.ai-assessment]
verify_jwt = true

[functions.ai-teacher-chat-completion]
verify_jwt = true

[functions.calculate-topic-progress]
verify_jwt = true